#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_LOG_DIR/server.log 2>&1 &
set -x

if [[ -d "${OPENSHIFT_DATA_DIR}sonar" ]]
then
    cd $OPENSHIFT_DATA_DIR
    bin/linux-x86-64/sonar.sh start
else
     exit 0
fi