#!/bin/bash
# The logic to stop your application should be put in this script.
#kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
#exit 0

set -x
if [[ -d "${OPENSHIFT_DATA_DIR}sonar" ]]
then
    cd ${OPENSHIFT_DATA_DIR}sonar
    bin/linux-x86-64/sonar.sh stop
else
     exit 0
fi